// <auto-generated />
using System;
using Dal.Do;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dal.Migrations
{
    [DbContext(typeof(dbcontext))]
    [Migration("20250303110011_newdatabase")]
    partial class newdatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dal.Do.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customerId");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("customerName");

                    b.Property<int?>("RegularCustomerCustomerId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId")
                        .HasName("PK__customer__B611CB7DDB7E855B");

                    b.HasIndex("RegularCustomerCustomerId");

                    b.ToTable("customer", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Dal.Do.Debt", b =>
                {
                    b.Property<int>("DebtsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("debtsId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DebtsId"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customerId");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime")
                        .HasColumnName("date");

                    b.Property<bool?>("IsPaid")
                        .HasColumnType("bit")
                        .HasColumnName("isPaid");

                    b.Property<string>("Notes")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("notes");

                    b.Property<int?>("PaymentType")
                        .HasColumnType("int")
                        .HasColumnName("paymentType");

                    b.Property<int?>("SaleId")
                        .HasColumnType("int")
                        .HasColumnName("saleId");

                    b.Property<int?>("SumOfDebts")
                        .HasColumnType("int")
                        .HasColumnName("sumOfDebts");

                    b.HasKey("DebtsId")
                        .HasName("PK__debts__A8B8A7A22D877B9D");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PaymentType");

                    b.HasIndex("SaleId");

                    b.ToTable("debts", (string)null);
                });

            modelBuilder.Entity("Dal.Do.PaymentType", b =>
                {
                    b.Property<int>("PaymentCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("paymentCode");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentCode"));

                    b.Property<string>("TypeOfpayment")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("typeOfpayment");

                    b.HasKey("PaymentCode")
                        .HasName("PK__paymentT__B5D907FA77B963B5");

                    b.ToTable("paymentType", (string)null);
                });

            modelBuilder.Entity("Dal.Do.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .HasColumnType("int")
                        .HasColumnName("saleId");

                    b.Property<string>("EventTime")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("eventTime");

                    b.Property<string>("SaleName")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("saleName");

                    b.HasKey("SaleId")
                        .HasName("PK__sales__FAE8F4F53AE00377");

                    b.ToTable("sales", (string)null);
                });

            modelBuilder.Entity("Dal.Do.RegularCustomer", b =>
                {
                    b.HasBaseType("Dal.Do.Customer");

                    b.Property<bool?>("Activy")
                        .HasColumnType("bit")
                        .HasColumnName("activy");

                    b.Property<string>("Address")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("address");

                    b.Property<string>("DefaultPhone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("defaultPhone");

                    b.Property<string>("Fax")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("fax");

                    b.Property<string>("HomePhone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("homePhone");

                    b.Property<string>("Mail")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("mail");

                    b.ToTable("regularCustomer", (string)null);
                });

            modelBuilder.Entity("Dal.Do.Customer", b =>
                {
                    b.HasOne("Dal.Do.RegularCustomer", "RegularCustomer")
                        .WithMany()
                        .HasForeignKey("RegularCustomerCustomerId");

                    b.Navigation("RegularCustomer");
                });

            modelBuilder.Entity("Dal.Do.Debt", b =>
                {
                    b.HasOne("Dal.Do.Customer", "Customer")
                        .WithMany("Debts")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK__debts__customerI__403A8C7D");

                    b.HasOne("Dal.Do.PaymentType", "PaymentTypeNavigation")
                        .WithMany("Debts")
                        .HasForeignKey("PaymentType")
                        .HasConstraintName("FK__debts__paymentTy__4222D4EF");

                    b.HasOne("Dal.Do.Sale", "Sale")
                        .WithMany("Debts")
                        .HasForeignKey("SaleId")
                        .HasConstraintName("FK__debts__saleId__412EB0B6");

                    b.Navigation("Customer");

                    b.Navigation("PaymentTypeNavigation");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Dal.Do.RegularCustomer", b =>
                {
                    b.HasOne("Dal.Do.Customer", null)
                        .WithOne()
                        .HasForeignKey("Dal.Do.RegularCustomer", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dal.Do.Customer", b =>
                {
                    b.Navigation("Debts");
                });

            modelBuilder.Entity("Dal.Do.PaymentType", b =>
                {
                    b.Navigation("Debts");
                });

            modelBuilder.Entity("Dal.Do.Sale", b =>
                {
                    b.Navigation("Debts");
                });
#pragma warning restore 612, 618
        }
    }
}
